# Generated by Django 5.0.6 on 2024-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
